# Generated by Django 3.2.5 on 2022-05-11 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_auto_20220511_1749'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='user',
            new_name='userz',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='user',
            new_name='userz',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='user',
            new_name='userz',
        ),
        migrations.RenameField(
            model_name='medicine',
            old_name='user',
            new_name='userz',
        ),
    ]
